#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command
repo init --depth=1 --no-repo-verify -u https://github.com/Bootleggers-BrokenLab/manifest -b sambunimbo -g default,-mips,-darwin,-notdefault

# Local manifest
git clone https://github.com/anyinglulu1/local_manifest.git --depth 1 -b Bootleggers .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
