#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

 sudo apt-get install neofetch
 neofetch

# Repo init command
repo init --depth=1 --no-repo-verify -u https://github.com/projectarcana-aosp/manifest -b 12.x -g default,-mips,-darwin,-notdefault

# Local manifest
git clone https://github.com/anyinglulu1/local_manifest.git --depth 1 -b Arcana-Whyred .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again
repo sync --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune
